<?php
session_start();
if (isset($_SESSION['user_id'])) {
    $dashboardPerRole = ['admin' => 'admin-dashboard', 'kabalai' => 'kabalai-dashboard'];
    header('Location: ' . ($dashboardPerRole[$_SESSION['role'] ?? ''] ?? 'dashboard'));
    exit;
}
?>
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="GAS-PAMAN adalah platform digital BBPOM di Mataram untuk edukasi obat dan makanan aman di komunitas.">
    <title>GAS-PAMAN | Keluarga Sadar Obat dan Makanan Aman</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <style>
        html { scroll-behavior:smooth; } body { font-family:'Plus Jakarta Sans',sans-serif; background:#fffaf7; color:#1f2937; }
        .grid-bg { background-image:linear-gradient(rgba(251,146,60,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(251,146,60,.08) 1px,transparent 1px); background-size:36px 36px; }
        .orb { animation:drift 9s ease-in-out infinite; } .orb-delay { animation-delay:-4.5s; } .floating-logo { animation:floatLogo 6s ease-in-out infinite; }
        .cta { position:relative; isolation:isolate; overflow:hidden; background:linear-gradient(115deg,#c2410c,#f97316 48%,#fbbf24); background-size:180% 180%; animation:gradientFlow 5s ease-in-out infinite; }
        .cta:after { content:''; position:absolute; z-index:-1; top:-80%; left:-45%; width:24%; height:260%; background:linear-gradient(90deg,transparent,rgba(255,255,255,.85),transparent); transform:skewX(-22deg); animation:flashRun 3.4s ease-in-out infinite; }
        .feature { transition:transform .25s ease,box-shadow .25s ease,border-color .25s ease; } .feature:hover { transform:translateY(-7px); border-color:#fed7aa; box-shadow:0 24px 45px -28px rgba(194,65,12,.42); }
        .step:not(:last-child):after { content:''; position:absolute; top:31px; left:50%; width:100%; height:1px; background:linear-gradient(90deg,#fed7aa,#fbbf24,#fed7aa); }
        @keyframes drift { 0%,100% { transform:translate(0,0) scale(1); } 50% { transform:translate(20px,-25px) scale(1.1); } }
        @keyframes floatLogo { 0%,100% { transform:translateY(0) rotate(-2deg); } 50% { transform:translateY(-15px) rotate(2deg); } }
        @keyframes gradientFlow { 0%,100% { background-position:0% 50%; } 50% { background-position:100% 50%; } }
        @keyframes flashRun { 0%,20% { left:-45%; } 52%,100% { left:130%; } }
        @media(max-width:767px) { .step:not(:last-child):after { display:none; } }
        @media(prefers-reduced-motion:reduce) { *,*:before,*:after { animation-duration:.01ms!important; animation-iteration-count:1!important; scroll-behavior:auto!important; } }
    </style>
</head>
<body>
    <header class="absolute inset-x-0 top-0 z-20">
        <nav class="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8">
            <a href="index" class="flex items-center gap-3" aria-label="Beranda GAS-PAMAN">
                <span class="flex h-11 w-11 items-center justify-center overflow-hidden rounded-2xl bg-white p-1 shadow-lg shadow-orange-900/10 ring-1 ring-orange-100"><img src="views/gas-paman-round.png" alt="Logo GAS-PAMAN" class="h-full w-full object-cover"></span>
                <span><strong class="block text-sm font-black tracking-tight text-red-900">GAS-PAMAN</strong><small class="block text-[8px] font-black tracking-[.22em] text-orange-600">BBPOM DI MATARAM</small></span>
            </a>
            <div class="hidden items-center gap-7 text-[11px] font-extrabold uppercase tracking-widest text-slate-600 md:flex"><a class="hover:text-orange-600" href="#tentang">Tentang</a><a class="hover:text-orange-600" href="#fitur">Fitur</a><a class="hover:text-orange-600" href="#alur">Alur</a></div>
            <a href="login" class="rounded-xl border border-orange-200 bg-white/90 px-4 py-2.5 text-[10px] font-black uppercase tracking-widest text-orange-700 shadow-sm transition hover:border-orange-400 hover:bg-orange-50">Masuk</a>
        </nav>
    </header>
    <main>
        <section class="grid-bg relative isolate overflow-hidden bg-gradient-to-br from-[#fffaf7] via-[#fff8ed] to-[#fff1e6] pt-32">
            <div class="orb absolute -left-24 top-32 -z-10 h-72 w-72 rounded-full bg-orange-300/30"></div><div class="orb orb-delay absolute right-0 top-10 -z-10 h-96 w-96 rounded-full bg-amber-200/40"></div>
            <div class="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 md:px-8 lg:grid-cols-[1.1fr_.9fr] lg:pb-28">
                <div class="max-w-2xl">
                    <div class="mb-6 inline-flex items-center gap-2 rounded-full border border-orange-200 bg-white/75 px-4 py-2 text-[9px] font-black uppercase tracking-[.18em] text-orange-700 shadow-sm"><span class="h-2 w-2 animate-pulse rounded-full bg-orange-500"></span> Platform Edukasi Digital BBPOM Mataram</div>
                    <h1 class="text-4xl font-black leading-[1.08] tracking-tight text-slate-900 sm:text-5xl lg:text-6xl">Edukasi aman, <span class="bg-gradient-to-r from-red-800 via-orange-600 to-amber-500 bg-clip-text text-transparent">dampak nyata</span> untuk keluarga.</h1>
                    <p class="mt-6 max-w-xl text-base font-medium leading-8 text-slate-600">GAS-PAMAN membantu agen dan BBPOM di Mataram mencatat, memantau, serta menguatkan edukasi obat dan makanan aman hingga ke komunitas.</p>
                    <div class="mt-8 flex flex-wrap gap-3"><a href="login" class="cta inline-flex items-center gap-3 rounded-2xl px-6 py-4 text-[11px] font-black uppercase tracking-widest text-white shadow-xl shadow-orange-600/25 transition hover:-translate-y-1"><i class="fas fa-right-to-bracket"></i> Masuk ke Sistem</a><a href="register" class="inline-flex items-center gap-3 rounded-2xl border border-orange-200 bg-white px-6 py-4 text-[11px] font-black uppercase tracking-widest text-orange-700 shadow-sm transition hover:-translate-y-1 hover:border-orange-400"><i class="fas fa-user-plus"></i> Daftar Kader</a></div>
                    <div class="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-xs font-bold text-slate-500"><span><i class="fas fa-circle-check mr-2 text-orange-500"></i>Laporan terstruktur</span><span><i class="fas fa-circle-check mr-2 text-orange-500"></i>Monitoring real-time</span><span><i class="fas fa-circle-check mr-2 text-orange-500"></i>Evaluasi kader</span></div>
                </div>
                <div class="relative mx-auto w-full max-w-md"><div class="absolute inset-8 rounded-[42px] bg-gradient-to-br from-orange-400 to-amber-300 opacity-30 blur-3xl"></div><div class="relative rounded-[38px] border border-white/80 bg-white/75 p-5 shadow-2xl shadow-orange-900/15 backdrop-blur-xl"><div class="flex items-center justify-between rounded-[26px] bg-red-900 p-5 text-white"><div><p class="text-[9px] font-black uppercase tracking-[.18em] text-orange-300">GAS-PAMAN</p><p class="mt-1 text-lg font-black">Ruang Edukasi</p></div><span class="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/10 text-xl text-orange-300"><i class="fas fa-shield-heart"></i></span></div><div class="floating-logo relative mx-auto -my-3 flex h-[280px] items-center justify-center"><div class="absolute h-52 w-52 rounded-full border border-dashed border-orange-300"></div><img src="views/logo-gas-paman.png" alt="Ilustrasi GAS-PAMAN" class="relative h-[264px] w-full object-contain drop-shadow-xl"></div><div class="grid grid-cols-3 gap-3"><div class="rounded-2xl bg-orange-50 p-3 text-center"><i class="fas fa-pen-to-square text-orange-600"></i><p class="mt-2 text-[8px] font-black uppercase text-slate-500">Catat</p></div><div class="rounded-2xl bg-amber-50 p-3 text-center"><i class="fas fa-chart-line text-amber-600"></i><p class="mt-2 text-[8px] font-black uppercase text-slate-500">Pantau</p></div><div class="rounded-2xl bg-red-50 p-3 text-center"><i class="fas fa-people-group text-red-700"></i><p class="mt-2 text-[8px] font-black uppercase text-slate-500">Berdaya</p></div></div></div></div>
            </div>
            <div class="border-y border-orange-100 bg-white/70 py-4 backdrop-blur"><div class="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-10 gap-y-2 px-5 text-[9px] font-black uppercase tracking-[.18em] text-slate-400"><span>Integrasi Laporan</span><span class="text-orange-400">✦</span><span>Penguatan Kader</span><span class="text-orange-400">✦</span><span>Obat & Makanan Aman</span></div></div>
        </section>
        <section id="tentang" class="bg-white py-20 md:py-28"><div class="mx-auto grid max-w-7xl gap-12 px-5 md:px-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p class="text-[10px] font-black uppercase tracking-[.2em] text-orange-600">Tujuan GAS-PAMAN</p><h2 class="mt-4 text-3xl font-black leading-tight tracking-tight text-slate-900 md:text-4xl">Menjadikan informasi aman lebih dekat dengan setiap keluarga.</h2></div><div class="rounded-[32px] border border-orange-100 bg-gradient-to-br from-orange-50 to-amber-50 p-7 md:p-9"><p class="text-base font-medium leading-8 text-slate-600">GAS-PAMAN — <strong class="text-red-800">Keluarga Sadar Obat dan Makanan Aman</strong> — adalah platform digital untuk mendukung agen dalam menyampaikan edukasi, mendokumentasikan kegiatan, dan membantu BBPOM di Mataram memantau dampak program secara akurat.</p><div class="mt-7 grid gap-4 sm:grid-cols-2"><div class="rounded-2xl bg-white p-4 shadow-sm"><i class="fas fa-bullseye text-orange-600"></i><p class="mt-3 text-sm font-black text-slate-800">Mendorong kesadaran</p><p class="mt-1 text-xs leading-5 text-slate-500">Tentang pemilihan dan penggunaan obat serta pangan yang aman.</p></div><div class="rounded-2xl bg-white p-4 shadow-sm"><i class="fas fa-tower-broadcast text-orange-600"></i><p class="mt-3 text-sm font-black text-slate-800">Memperluas jangkauan</p><p class="mt-1 text-xs leading-5 text-slate-500">Edukasi yang konsisten dari kader ke masyarakat di berbagai komunitas.</p></div></div></div></div></section>
        <section id="fitur" class="bg-[#fffaf7] py-20 md:py-28"><div class="mx-auto max-w-7xl px-5 md:px-8"><div class="mx-auto max-w-2xl text-center"><p class="text-[10px] font-black uppercase tracking-[.2em] text-orange-600">Satu platform, dampak terukur</p><h2 class="mt-4 text-3xl font-black tracking-tight text-slate-900 md:text-4xl">Dirancang untuk kerja lapangan yang lebih sederhana.</h2></div><div class="mt-12 grid gap-5 md:grid-cols-3"><article class="feature rounded-[28px] border border-orange-100 bg-white p-7"><span class="flex h-12 w-12 items-center justify-center rounded-2xl bg-orange-100 text-xl text-orange-600"><i class="fas fa-file-circle-plus"></i></span><h3 class="mt-6 text-lg font-black text-slate-900">Laporan kegiatan</h3><p class="mt-3 text-sm leading-6 text-slate-500">Catat edukasi komunitas, data penerima manfaat, lokasi, dan bukti kegiatan dalam satu alur.</p></article><article class="feature rounded-[28px] border border-orange-100 bg-white p-7"><span class="flex h-12 w-12 items-center justify-center rounded-2xl bg-amber-100 text-xl text-amber-600"><i class="fas fa-chart-pie"></i></span><h3 class="mt-6 text-lg font-black text-slate-900">Monitoring terarah</h3><p class="mt-3 text-sm leading-6 text-slate-500">Admin dapat meninjau laporan, melihat rangkuman data, dan menyiapkan kebutuhan pelaporan internal.</p></article><article class="feature rounded-[28px] border border-orange-100 bg-white p-7"><span class="flex h-12 w-12 items-center justify-center rounded-2xl bg-red-100 text-xl text-red-700"><i class="fas fa-graduation-cap"></i></span><h3 class="mt-6 text-lg font-black text-slate-900">Evaluasi pengetahuan</h3><p class="mt-3 text-sm leading-6 text-slate-500">Pre-test dan post-test membantu mengukur penguatan pengetahuan para agen secara berkelanjutan.</p></article></div></div></section>
        <section id="alur" class="bg-red-900 py-20 text-white md:py-28"><div class="mx-auto max-w-7xl px-5 md:px-8"><div class="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p class="text-[10px] font-black uppercase tracking-[.2em] text-orange-300">Alur kerja yang jelas</p><h2 class="mt-4 text-3xl font-black tracking-tight md:text-4xl">Dari edukasi menjadi data yang bermakna.</h2></div><a href="login" class="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-orange-300 hover:text-white">Mulai sekarang <i class="fas fa-arrow-right"></i></a></div><div class="mt-12 grid gap-8 md:grid-cols-3"><div class="step relative"><span class="relative z-10 flex h-16 w-16 items-center justify-center rounded-2xl border border-orange-300/40 bg-white/10 text-xl font-black text-orange-300">01</span><h3 class="mt-6 text-lg font-black">Agen mengedukasi</h3><p class="mt-2 text-sm leading-6 text-white/65">Menyampaikan informasi obat dan makanan aman kepada masyarakat.</p></div><div class="step relative"><span class="relative z-10 flex h-16 w-16 items-center justify-center rounded-2xl border border-orange-300/40 bg-white/10 text-xl font-black text-orange-300">02</span><h3 class="mt-6 text-lg font-black">Kegiatan terdokumentasi</h3><p class="mt-2 text-sm leading-6 text-white/65">Laporan dan bukti kegiatan dikirim melalui sistem secara terstruktur.</p></div><div class="step relative"><span class="relative z-10 flex h-16 w-16 items-center justify-center rounded-2xl border border-orange-300/40 bg-white/10 text-xl font-black text-orange-300">03</span><h3 class="mt-6 text-lg font-black">Dampak dipantau</h3><p class="mt-2 text-sm leading-6 text-white/65">BBPOM memperoleh data untuk review, evaluasi, dan penguatan program.</p></div></div></div></section>
        <section class="bg-white py-20"><div class="mx-auto max-w-4xl px-5 text-center md:px-8"><div class="rounded-[36px] border border-orange-100 bg-gradient-to-br from-orange-50 to-amber-50 px-6 py-12 shadow-xl shadow-orange-900/5 md:px-12"><p class="text-[10px] font-black uppercase tracking-[.2em] text-orange-600">Bersama untuk keluarga yang lebih sadar</p><h2 class="mx-auto mt-4 max-w-2xl text-3xl font-black tracking-tight text-slate-900 md:text-4xl">Mulai perjalanan edukasi aman Anda bersama GAS-PAMAN.</h2><div class="mt-8 flex flex-wrap justify-center gap-3"><a href="login" class="cta inline-flex items-center gap-3 rounded-2xl px-6 py-4 text-[11px] font-black uppercase tracking-widest text-white shadow-xl shadow-orange-600/25"><i class="fas fa-right-to-bracket"></i> Masuk Sistem</a><a href="register" class="inline-flex items-center gap-3 rounded-2xl border border-orange-200 bg-white px-6 py-4 text-[11px] font-black uppercase tracking-widest text-orange-700"><i class="fas fa-user-plus"></i> Daftar Kader</a></div></div></div></section>
    </main>
    <footer class="bg-slate-950 py-8 text-center"><p class="text-xs font-bold text-white/60">© <?= date('Y') ?> BBPOM di Mataram · GAS-PAMAN</p><p class="mt-2 text-[9px] font-black uppercase tracking-[.2em] text-orange-400">Keluarga Sadar Obat dan Makanan Aman</p></footer>
</body>
</html>
